plugins {
	id 'java'
	id 'org.springframework.boot' version '3.3.1'
	id 'io.spring.dependency-management' version '1.1.6'
}

group = 'com.kongdak'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// Spring Boot Starters
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-webflux'

	// Redis
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'

	// JWT 관련 의존성
	implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'

	// Spring Security
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
	implementation 'org.springframework.boot:spring-boot-starter-security'

	// AWS 의존성 추가
	implementation platform('io.awspring.cloud:spring-cloud-aws-dependencies:3.0.1')
	implementation 'io.awspring.cloud:spring-cloud-aws-starter'
	implementation 'software.amazon.awssdk:aws-core:2.20.63'
	implementation 'software.amazon.awssdk:ssm:2.20.63'
//  implementation 'io.awspring.cloud:spring-cloud-aws-starter-s3'

	// AWS CloudWatch 의존성 추가
	implementation 'ca.pjer:logback-awslogs-appender:1.6.0'

	// Swagger
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.0.2'
	// Swagger 어노테이션 처리
	implementation 'org.springdoc:springdoc-openapi-starter-common:2.0.2'

	// Kafka
	implementation 'org.springframework.kafka:spring-kafka'

	// Lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	// AOP
	implementation 'org.springframework.boot:spring-boot-starter-aop'

	// Dev Tools
	developmentOnly 'org.springframework.boot:spring-boot-devtools'

	// Database
	runtimeOnly 'org.mariadb.jdbc:mariadb-java-client'

	// Test Dependencies
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.kafka:spring-kafka-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

}

tasks.named('test') {
	useJUnitPlatform()
}
